//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayController) DeepCopyInto(out *GatewayController) {
	*out = *in
	if in.ControllerNames != nil {
		in, out := &in.ControllerNames, &out.ControllerNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayController.
func (in *GatewayController) DeepCopy() *GatewayController {
	if in == nil {
		return nil
	}
	out := new(GatewayController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesWatchConfig) DeepCopyInto(out *KubernetesWatchConfig) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesWatchConfig.
func (in *KubernetesWatchConfig) DeepCopy() *KubernetesWatchConfig {
	if in == nil {
		return nil
	}
	out := new(KubernetesWatchConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rudder) DeepCopyInto(out *Rudder) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rudder.
func (in *Rudder) DeepCopy() *Rudder {
	if in == nil {
		return nil
	}
	out := new(Rudder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Rudder) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RudderList) DeepCopyInto(out *RudderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Rudder, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RudderList.
func (in *RudderList) DeepCopy() *RudderList {
	if in == nil {
		return nil
	}
	out := new(RudderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RudderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RudderSpec) DeepCopyInto(out *RudderSpec) {
	*out = *in
	if in.GatewayController != nil {
		in, out := &in.GatewayController, &out.GatewayController
		*out = new(GatewayController)
		(*in).DeepCopyInto(*out)
	}
	if in.XdsServerConfig != nil {
		in, out := &in.XdsServerConfig, &out.XdsServerConfig
		*out = new(XdsServerConfig)
		**out = **in
	}
	if in.KubernetesWatchConfig != nil {
		in, out := &in.KubernetesWatchConfig, &out.KubernetesWatchConfig
		*out = new(KubernetesWatchConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RudderSpec.
func (in *RudderSpec) DeepCopy() *RudderSpec {
	if in == nil {
		return nil
	}
	out := new(RudderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RudderStatus) DeepCopyInto(out *RudderStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RudderStatus.
func (in *RudderStatus) DeepCopy() *RudderStatus {
	if in == nil {
		return nil
	}
	out := new(RudderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XdsServerConfig) DeepCopyInto(out *XdsServerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XdsServerConfig.
func (in *XdsServerConfig) DeepCopy() *XdsServerConfig {
	if in == nil {
		return nil
	}
	out := new(XdsServerConfig)
	in.DeepCopyInto(out)
	return out
}
