apiVersion: config.rudder.kubergate.io/v1alpha1
kind: Rudder
metadata:
  name: RudderConfig
spec:
  gatewayController:
    controllerNames:
      - rudder.kubergate.io/gatewayclass-controller-1
      - rudder.kubergate.io/gatewayclass-controller-2
  xdsServerConfig:
    xdsMode: XDS_DELTA
  kubernetesWatchConfig:
    namespaces:
      - kubergate-ns-1
      - kubergate-ns-2
  dataStoreConfig:
    dbPath: ./rudderdb
    timeout: 300
  